### ISSUE TITLE
Api is not a constructor

### ISSUE THREAD

**Issue by redline187** [sabersalv/flood-api#3]
im getting this error

```
file:///home/redline/test/test.js:3
const api = new Api({
            ^

TypeError: Api is not a constructor
    at file:///home/xxx/test/test.js:3:13
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

```
```
const api = new Api({
  baseUrl: 'http://localhost:3000/api',
  username: 'xxxx',
  password: 'xxxx',
})

api.options.baseUrl
await api.client.connectionTest()
```
how can i load this script?

**Comment by moussetik** [comment]
Hello,

I have exactly the same problem !
I'm not very familiar with imports done this way (ESM I think?)

I have been looking for 2 days, but nothing helps, I do not understand why I have the same error.

Could you tell me how you solved your problem?

-----------

For information, I proceeded like this:
- npm init
- npm i flood-api
- new file at the root:
```
import Api from 'flood-api'

const api = new Api({
  baseUrl: 'http://localhost:3000/api',
  username: 'user',
  password: 'pass',
})

await api.client.connectionTest()
//-> { status, url, headers, data }
```

**Comment by sabersalv** [comment]
@moussetik Try

```js
const Api = require('flood-api').default

async function main() {
  const api = new Api({
    baseUrl: 'http://localhost:3000/api',
    username: 'user',
    password: 'pass',
  })

  await api.client.connectionTest()
}

main()
```
